name 'b4ldr-logrotate'
version '1.1.2'
source 'https://github.com/b4ldr/puppet-logrotate'
license 'MIT'
summary 'Logrotate module'
description 'Manage logrotate on your servers with Puppet, update of https://github.com/rodjek/puppet-logrotate adding outstanding merges'
project_page 'https://github.com/b4ldr/puppet-logrotate'
